import type { AppProps } from 'next/app'
import Head from 'next/head'
// import Store, { persistor } from  "../stores/redux";

import { Provider } from 'react-redux';
import store, { persistor } from '../stores/redux';
import { PersistGate } from "redux-persist/integration/react";
import ToastContextProvider from '../stores/context/toastContext';

import '../styles/globals.css'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <ToastContextProvider>
            <Component {...pageProps} />
          </ToastContextProvider>
        </PersistGate>
      </Provider>
    </>
  )
}
